apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  labels:
    service: user-app
spec:
  replicas: 3
  selector:
    matchLabels:
      service: user-app
  template:
    metadata:
      labels:
        service: user-app
    spec:
      containers:
      - name: microservice-user
        image: sjulian/microservice-user:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always