apiVersion: v1
kind: Service
metadata:
  labels:
    service: user-svc
  name: user-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    service: user-app
  type: ClusterIP